// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BeautyCenter_.Net_Angular.Models;

[Table("Service")]
public partial class Service
{
    [Key]
    public int Id { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Price { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Category { get; set; }

    [InverseProperty("Service")]
    public virtual ICollection<UserService> ?UserServices { get; set; } = new List<UserService>();

    [ForeignKey("ServiceId")]
    [InverseProperty("Services")]
    public virtual ICollection<Package> ?Packages { get; set; } = new List<Package>();
}